import { INodeProperties } from 'n8n-workflow';

export const dealOperations: INodeProperties[] = [
	{
		displayName: 'Operação',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['deal'] } },
		options: [
			{ name: 'Criar', value: 'create', description: 'Cria uma negociação', action: 'Criar uma negociação' },
			{ name: 'Obter', value: 'get', description: 'Busca uma negociação pelo ID', action: 'Obter uma negociação' },
			{ name: 'Obter Vários', value: 'getAll', description: 'Lista negociações com filtros', action: 'Obter várias negociações' },
			{ name: 'Atualizar', value: 'update', description: 'Atualiza uma negociação (inclui mover etapa e ganhar/perder)', action: 'Atualizar uma negociação' },
			{ name: 'Deletar', value: 'delete', description: 'Remove uma negociação', action: 'Deletar uma negociação' },
		],
		default: 'getAll',
	},
];

export const dealFields: INodeProperties[] = [
	// --- ID (get / update / delete) ---
	{
		displayName: 'ID Da Negociação',
		name: 'dealId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['deal'], operation: ['get', 'update', 'delete'] } },
		default: '',
		description: 'O ID (UUID) da negociação',
	},
	// --- create obrigatórios ---
	{
		displayName: 'Título',
		name: 'title',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['deal'], operation: ['create'] } },
		default: '',
		description: 'Título da negociação',
	},
	{
		displayName: 'Nome Do Lead',
		name: 'lead_name',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['deal'], operation: ['create'] } },
		default: '',
		description: 'Nome do lead/contato da negociação',
	},
	{
		displayName: 'Funil',
		name: 'pipeline_id',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getPipelines' },
		required: true,
		displayOptions: { show: { resource: ['deal'], operation: ['create'] } },
		default: '',
		description: 'Funil (pipeline) da negociação',
	},
	{
		displayName: 'Etapa',
		name: 'stage_id',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getStages', loadOptionsDependsOn: ['pipeline_id'] },
		required: true,
		displayOptions: { show: { resource: ['deal'], operation: ['create'] } },
		default: '',
		description: 'Etapa dentro do funil selecionado',
	},
	{
		displayName: 'Responsável',
		name: 'responsavel_profile_id',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getOwners' },
		required: true,
		displayOptions: { show: { resource: ['deal'], operation: ['create'] } },
		default: '',
		description: 'Responsável pela negociação',
	},
	// --- create: campos opcionais ---
	{
		displayName: 'Campos Adicionais',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Adicionar campo',
		default: {},
		displayOptions: { show: { resource: ['deal'], operation: ['create'] } },
		options: [
			{ displayName: 'Valor (centavos)', name: 'value_cents', type: 'number', default: 0, description: 'Valor da negociação em centavos' },
			{ displayName: 'Telefone Do Lead', name: 'lead_phone', type: 'string', default: '' },
			{ displayName: 'E-mail Do Lead', name: 'lead_email', type: 'string', default: '' },
			{ displayName: 'ID Do Paciente', name: 'patient_id', type: 'string', default: '', description: 'UUID de um paciente da organização' },
			{ displayName: 'Canal De Origem', name: 'source_channel_id', type: 'options', typeOptions: { loadOptionsMethod: 'getSourceChannels' }, default: '' },
			{ displayName: 'Detalhe Da Origem', name: 'source_detail', type: 'string', default: '' },
			{ displayName: 'Data Prevista De Fechamento', name: 'expected_close_date', type: 'string', default: '', description: 'Formato YYYY-MM-DD' },
			{ displayName: 'Observações', name: 'observations', type: 'string', typeOptions: { rows: 3 }, default: '' },
			{ displayName: 'UTM Source', name: 'utm_source', type: 'string', default: '' },
			{ displayName: 'UTM Medium', name: 'utm_medium', type: 'string', default: '' },
			{ displayName: 'UTM Campaign', name: 'utm_campaign', type: 'string', default: '' },
			{ displayName: 'UTM Term', name: 'utm_term', type: 'string', default: '' },
			{ displayName: 'UTM Content', name: 'utm_content', type: 'string', default: '' },
		],
	},
	// --- update: seletor de etapa (top-level p/ loadOptions ter contexto de funil) ---
	{
		displayName: 'Funil (para escolher a etapa)',
		name: 'pipeline_id',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getPipelines' },
		displayOptions: { show: { resource: ['deal'], operation: ['update'] } },
		default: '',
		description: 'Selecione o funil apenas para listar as etapas. Não é enviado à API.',
	},
	{
		displayName: 'Nova Etapa',
		name: 'stage_id',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getStages', loadOptionsDependsOn: ['pipeline_id'] },
		displayOptions: { show: { resource: ['deal'], operation: ['update'] } },
		default: '',
		description: 'Mover a negociação para esta etapa (opcional)',
	},
	// --- update: campos ---
	{
		displayName: 'Campos A Atualizar',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Adicionar campo',
		default: {},
		displayOptions: { show: { resource: ['deal'], operation: ['update'] } },
		options: [
			{ displayName: 'Título', name: 'title', type: 'string', default: '' },
			{ displayName: 'Status', name: 'status', type: 'options', options: [ { name: 'Aberta', value: 'open' }, { name: 'Ganha', value: 'won' }, { name: 'Perdida', value: 'lost' } ], default: 'open' },
			{ displayName: 'Motivo Da Perda', name: 'loss_reason_id', type: 'options', typeOptions: { loadOptionsMethod: 'getLossReasons' }, default: '' },
			{ displayName: 'Detalhe Da Perda', name: 'loss_detail', type: 'string', default: '' },
			{ displayName: 'Responsável', name: 'responsavel_profile_id', type: 'options', typeOptions: { loadOptionsMethod: 'getOwners' }, default: '' },
			{ displayName: 'Valor (centavos)', name: 'value_cents', type: 'number', default: 0 },
			{ displayName: 'Nome Do Lead', name: 'lead_name', type: 'string', default: '' },
			{ displayName: 'Telefone Do Lead', name: 'lead_phone', type: 'string', default: '' },
			{ displayName: 'E-mail Do Lead', name: 'lead_email', type: 'string', default: '' },
			{ displayName: 'Serviço', name: 'service_id', type: 'options', typeOptions: { loadOptionsMethod: 'getServices' }, default: '' },
			{ displayName: 'Data Prevista De Fechamento', name: 'expected_close_date', type: 'string', default: '', description: 'Formato YYYY-MM-DD' },
			{ displayName: 'Observações', name: 'observations', type: 'string', typeOptions: { rows: 3 }, default: '' },
			{ displayName: 'UTM Source', name: 'utm_source', type: 'string', default: '' },
			{ displayName: 'UTM Medium', name: 'utm_medium', type: 'string', default: '' },
			{ displayName: 'UTM Campaign', name: 'utm_campaign', type: 'string', default: '' },
			{ displayName: 'UTM Term', name: 'utm_term', type: 'string', default: '' },
			{ displayName: 'UTM Content', name: 'utm_content', type: 'string', default: '' },
		],
	},
	// --- Campos personalizados (create + update) ---
	{
		displayName: 'Campos Personalizados',
		name: 'customFields',
		type: 'fixedCollection',
		typeOptions: { multipleValues: true },
		placeholder: 'Adicionar campo personalizado',
		default: {},
		displayOptions: { show: { resource: ['deal'], operation: ['create', 'update'] } },
		options: [
			{
				name: 'field',
				displayName: 'Campo',
				values: [
					{ displayName: 'Campo', name: 'field_id', type: 'options', typeOptions: { loadOptionsMethod: 'getCustomFields' }, default: '', description: 'Campo personalizado da organização' },
					{ displayName: 'Valor', name: 'value', type: 'string', default: '', description: 'Para campos de seleção, informe o rótulo (ou o ID) da opção' },
				],
			},
		],
	},
	// --- getAll ---
	{
		displayName: 'Retornar Todos',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: { show: { resource: ['deal'], operation: ['getAll'] } },
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limite',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		displayOptions: { show: { resource: ['deal'], operation: ['getAll'], returnAll: [false] } },
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filtros',
		name: 'filters',
		type: 'collection',
		placeholder: 'Adicionar filtro',
		default: {},
		displayOptions: { show: { resource: ['deal'], operation: ['getAll'] } },
		options: [
			{ displayName: 'Funil', name: 'pipeline_id', type: 'options', typeOptions: { loadOptionsMethod: 'getPipelines' }, default: '' },
			{ displayName: 'Status', name: 'status', type: 'options', options: [ { name: 'Aberta', value: 'open' }, { name: 'Ganha', value: 'won' }, { name: 'Perdida', value: 'lost' } ], default: 'open' },
			{ displayName: 'Responsável', name: 'responsavel_profile_id', type: 'options', typeOptions: { loadOptionsMethod: 'getOwners' }, default: '' },
			{ displayName: 'Busca (título)', name: 'q', type: 'string', default: '' },
		],
	},
];
